### ISSUE TITLE
Support of Kibana 5.5

### ISSUE THREAD

**Issue by v01t** [datavoyagerhk/kibana-pivot-table#2]
Hello,

thanks for exciting plugin, is there any way to use it with Kibana 5.5.x version, currently with a changed package.json for version 5.5.1, I get:
`Uncaught TypeError: __webpack_require__(...).register is not a function`

Version: 5.5.1
Build: 15405

Thanks.

**Comment by Prinkesh** [comment]
Any solution to this ? I was also facing the same issue .

**Comment by pikewong** [comment]
The team is working on supporting Kibana 5.6.1.  Would be released real soon.

**Comment by odmby** [comment]
We are really looking forward for an update for newer versions.
When do you expect it might be ready?

**Comment by v01t** [comment]
Maybe it makes sense to skip 5.5 and jump to 6.x support (or implement them as branches), as it may happen that most of the customers will use already ES 6.x when support of 5.5 will be implemented.
